
name = "DashGallery"
uuid = "1b08a953-4be3-4667-9a23-bb7a89da1e7f"
authors = ["Innowade.tech <wade@innowade.tech>"]
version = "0.0.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3"
